apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1

  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp

    spec:
      containers:
        - name: webapp
          image: ghcr.io/practical-devops/k8/web-app:latest

          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: rails-master-key

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: database-url

          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service

spec:
  type: ClusterIP

  selector:
    app: webapp

  ports:
    - port: 80
      targetPort: 3000
